config/routes.rb
require "subdomain"
Trenato::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get "my_pets", :to => 'users#pets', :as => "my_pets"
  resources :pets
  resources :comments
  constraints(Subdomain) do
    resources :bookmarks
    resources :recommendations
    match "/" => 'splash#welcome', :via => "get" 
    get "/myframe", :to => "splash#myframe", :as => :myframe
    get '/place/:state/:city/:service/:business_name/:id', :to => "thin#show", :as => :show_thin_city, :constraints => { :business_name => /.*/}
    get "/place/:service/:business_name/:id", :to => "thin#show", :as => :show_thin, :constraints => { :business_name => /.*/ }
    get '/search(/:page)', :to => "deals#index", :as => :search_deals, constraints: {page: /[0-9]+/}
    get '/:state/:city(/:page)', :to => "deals#index", :as => :deals, constraints: {page: /[0-9]+/}
    get '/:state/:city/:service(/:page)', :to => "deals#index", :as => :service_deals, constraints: {page: /[0-9]+/}
    get "/:state/:city/:zip(/:page)", :to => "deals#index", :as => :zip_deals, constraints: {zip: /\d\d\d\d\d/, page: /[0-9]+/}
    get "/:state/:city/:zip/:service(/:page)", :to => "deals#index", :as => :zip_service_deals, constraints: {zip: /\d\d\d\d\d/, page: /[0-9]+/}
    resources :thin do
      member do
        post :update_reviews
      end
    end
    resources :location_autocomplete, :only => [:index]
  end

  
  
  get "/about", :to => "splash#about_us"
  get "/privacy", :to => "splash#privacy"
  get "/terms", :to => "splash#terms"
  root 'pets#index'
  
  

  

end

app/controllers/thin_controller.rb
class ThinController < ApplicationController


  def show
    @thin = ThinMerchant.where(:id => params[:id]).first
    if @thin
      set_up_recommendation_and_bookmark
      @login_modal = true if !current_user && (params[:recommend] || params[:bookmark])
      @rating , @review_count, @review_type = @thin.review_and_rating
      render "show"
    else
      begin
        redirect_to :back, :flash => { :error => "Sorry! Coulddef  not find the business." }
      rescue ActionController::RedirectBackError
        redirect_to root_path, :flash => { :error => "Sorry! Could not find the business." }
      end
    end
  end

  def update_reviews
    @thin = ThinMerchant.where(:id => params[:id]).first
    if @thin
      if params["review_type"] == "yelp"
        @thin.update_yelp_reviews(params)
      elsif params["review_type"] == "google"
        @thin.update_google_reviews(params)
      elsif params["review_type"] == "city"
        @thin.update_city_reviews(params)
      end
      render :text => "0k", :status => 200
    else
      render :text => "not_found", :status => 404
    end
  end

private

def set_up_recommendation_and_bookmark
  if current_user
    @bookmark, @bookmarked = current_user.bookmark_thin_or_find(@thin, params[:bookmark])
    @recommendation, @recommended = current_user.recommend_thin_or_find(@thin, params[:recommend])
  end
  flash.now[:notice] = "#{@thin.name} has been successfully bookmarked!" if @bookmark
  flash.now[:notice] = "Successfully recommended #{@thin.name}" if @recommendation
end

end

app/helpers/thin_helper.rb
module ThinHelper

  def thin_region_details(thin)
    db_zip = ZipCode.where(:zip => thin.zip.to_s).first if !thin.city.present? || !thin.state.present?
    city = thin.city.present? ? thin.city : db_zip.try(&:city)
    state = thin.state.present? ? thin.state : db_zip.try(&:state)
    return (city ? ("<span class='medium_text' itemprop='addressLocality'>" + city + "</span>").html_safe + ", " : "") + (("<span class='medium_text' itemprop='addressRegion'>" + state + "</span>").html_safe || "") + " " + ( "<span class='medium_text' itemprop='postalCode'>" + thin.zip.to_s + "</span>").html_safe
  end
end

app/views/thin/_ratings.html.erb
<div class="col-xs-12 col-sm-4" id="rating-side">
  <% if thin.yelp_rating && thin.yelp_rating > 0 %>
    <div  itemprop="aggregateRating" itemscope itemtype="http://schema.org/AggregateRating" class="my-small-rating">
      <meta itemprop="ratingValue" content="<%= thin.yelp_rating %>" />
      <meta itemprop="reviewCount" content="<%= thin.yelp_review_count %>" />
      <div data-phone="<%= thin.phone_number %>" data-lng="<%= thin.location["lon"] %>" data-city="<%= thin.city %>" data-yelp_id="<%= @thin.yelp_id ? @thin.yelp_id : false %>" data-state="<%= thin.state %>" data-addr1="<%= thin.street_address %>" data-thin_id="<%= thin.id %>" data-lat="<%= thin.location["lat"]%>" class="yelp_rating_widget" data-update="<%= (thin.yelp_reviews_updated_at.nil? || thin.yelp_reviews_updated_at < 1.month.ago) ? true : false %>">
        <%= yelp_rating(thin) %>
      </div>
    </div>
  <% else %>
     <div data-phone="<%= thin.phone_number %>" data-lng="<%= thin.location["lon"] %>" data-city="<%= thin.city %>" data-state="<%= thin.state %>" data-addr1="<%= thin.street_address %>" data-thin_id="<%= thin.id %>" data-update="<%= (thin.yelp_reviews_updated_at.nil? || thin.yelp_reviews_updated_at < 1.month.ago) ? true : false %>" data-lat="<%= thin.location["lat"]%>" class="yelp_rating_widget" data-update="true">
     </div>
  <% end %>
  <% if thin.city_reviews.present? %>
    <div data-phone="<%= thin.phone_number %>" data-lng="<%= thin.location["lon"] %>" data-city="<%= thin.city %>" data-state="<%= thin.state %>" data-addr1="<%= thin.street_address %>" data-thin_id="<%= thin.id %>" data-client_ip="<%= request.remote_ip %>" data-publisher="<%= CITY_PUBLISHER %>" data-lat="<%= thin.location["lat"]%>" class="city_rating_widget" data-update="<%= (thin.city_reviews_updated_at.nil? || thin.city_reviews_updated_at < 1.month.ago) ? true : false %>">
      <%= city_rating(thin) %>
    </div>
  <% else %>
     <div data-phone="<%= thin.phone_number %>" data-lng="<%= thin.location["lon"] %>" data-city="<%= thin.city %>" data-state="<%= thin.state %>" data-addr1="<%= thin.street_address %>" data-thin_id="<%= thin.id %>" data-client_ip="<%= request.remote_ip %>" data-publisher="<%= CITY_PUBLISHER %>" data-lat="<%= thin.location["lat"]%>" class="city_rating_widget" data-update="<%= (thin.city_reviews_updated_at.nil? || thin.city_reviews_updated_at < 1.month.ago) ? true : false %>">
     </div>
  <% end %>
  <% if thin.google_reviews.present? %>
  <% else %>
    <div data-phone="<%= thin.phone_number %>" data-lng="<%= thin.location["lon"] %>" data-city="<%= thin.city %>" data-state="<%= thin.state %>" data-addr1="<%= thin.street_address %>" data-thin_id="<%= thin.id %>" data-lat="<%= thin.location["lat"]%>" class="google_rating_widget" data-update="true">
    </div>
  <% end %>
  <% if @recommended %>
    <%= link_to "Recommended", (@thin.slug_path()), :class => "btn btn-zomato-gray bold", :disabled => "disabled" %>
  <% else %>
    <%= link_to "Recommend", (@thin.slug_path()+"?recommend=true"), :class => "btn btn-zomato-gray bold" %>
  <% end %>
  <% if @bookmarked %>
    <%= link_to "Bookmarked", (@thin.slug_path()), :class => "btn btn-zomato-gray bold", :disabled => "disabled" %>
  <% else %>
    <%= link_to "Bookmark", (@thin.slug_path()+"?bookmark=true"), :class => "btn btn-zomato-gray bold" %>
  <% end %>
</div>

app/views/thin/show.html.erb
<% content_for :title, "#{@thin.name}, #{@thin.service.name}: #{@thin.city || cookies[:city]}, #{@thin.state || cookies[:state]} - #{SITENAME} " %>
<% content_for :description, "Checkout #{@thin.service.name} from #{@thin.name} in #{params[:city]}, #{params[:state]}. - More Information on #{SITENAME}" %>
<div class="">
  <div class="container  main_index_container">
    <%#= render :partial => "shared/orange_filter" %>
    <div class="row">
      <div class="col-xs-12" style="margin-top: 20px;">
        <ol class="breadcrumb">
          <li itemscope itemtype="http://data-vocabulary.org/Breadcrumb"><%= link_to ("<span itemprop='title'>" + dstate + ", " + dcity + "</span>").html_safe, deals_path(:state => dstate, :city => dcity), :itemprop => "url", :title => "More deals in #{dcity}, #{dstate}" %>
          </li>
          <li itemscope itemtype="http://data-vocabulary.org/Breadcrumb">
            <%= link_to ("<span itemprop='title'>" + @thin.service.name + "</span>").html_safe, service_deals_path(:state => dstate, :city => dcity, :service => @thin.service.name), :itemprop => "url", :title => "More #{@thin.service.name} deals in #{dcity}, #{dstate}" %>
          </li>
          <li itemscope itemtype="http://data-vocabulary.org/Breadcrumb" class="active">
            <meta itemprop="url" content="<%= request.url %>" />
            <meta itemprop="title" content="Book Apoointment on <%= SITENAME %>" />
            <%= @thin.name %>
          </li>
        </ol>  
      </div>
      <div itemscope itemtype="http://schema.org/LocalBusiness"  class="col-xs-12">
        <meta itemprop="currenciesAccepted" content="USD">
        <meta itemprop="priceRange" content="<%= @thin.try(:price_range) == '$' ? '$' : '$$' %>" />
        <div class="main_page_deal white_container" id="deals_container">
          <div class="row with_border clearfix">
            <div class="col-xs-12 col-sm-3" >
              <div  class="text-center" style="padding-left: 10px; margin-bottom: 12px;">
                <%= image_tag @thin.service.image_url.sample.gsub("medium", "thumb"), :class => "img-thumbnail img-responsive", :itemprop => "logo" , :title => (@thin.service.name + " from " + @thin.name), :alt => ("Request appointment for " + @thin.service.name + " from " + @thin.name) %>
              </div>
              <div class="text-center">
                <%= render :partial => "shared/thin_share_bar", :locals => {:thin => @thin} %>
              </div>
            </div>
            <div class="col-xs-12 col-sm-5">
              <div class="deal_info">
                <h1 class="bold margin-0 margin-bottom-5">
                  <%= "#{@thin.name}" %>
                </h1>
                <div  itemprop="address" itemscope itemtype="http://schema.org/PostalAddress">
                  <p>
                    <% if @thin.street_address.present? %>
                      <span class="medium_text" itemprop="streetAddress"><%= @thin.street_address %></span><br />
                    <% end %>
                    <% if @thin.neighborhoods.present? %>
                      <span class='medium_text'><%= @thin.neighborhoods.join(", ") %></span><br />
                    <% end %>
                    <%= thin_region_details(@thin) %>
                    <br />                    
                    <% if @thin.website.present? %>
                      <meta itemprop="url" content="<%= @thin.website %>">
                      <%= link_to @thin.website, @thin.website , :target => "_blank", :class => "medium_text" %><br/>
                    <% end %>
                    <% if @thin.phone_number.present? %>
                      <span class='medium_text'>Phone: <span itemprop="telephone" class='medium_text'><%= @thin.phone_number %></span></span><br />
                    <% end %>
                    <div class="hidden" itemprop="geo" itemscope="" itemtype="http://schema.org/GeoCoordinates">
                      <meta content="37.773086" itemprop="latitude">37.773086
                      <meta content="-122.39499" itemprop="latitude">-122.39499
                    </div>
                    <% if @thin.parking.present? %>
                      <span class='medium_text'>Parking: <%= @thin.parking %></span><br />
                    <% end %>
                    <% if @thin.price_range.present? %>
                      <span class='medium_text'>Price Range: <%= @thin.price_range%></span><br/>
                    <% end %>
                  </p>
                </div>
              </div>
            </div>

            <%= render :partial => "ratings" , :locals => {:thin => @thin} %>
             </div> <!-- TODO This div is don't know why it ended here -->
            
          </div>
          
         

          <div class="row with_border">
            <div class="col-xs-6">
              <h3 class="medium_heading strong margin-top-0">Offerings</h3>
              <h2 class="medium_text"><%= @thin.all_services.to_sentence %></h2>
            </div>
            <% if @thin.hours.present? %>
              <% hours =  @thin.hours.class == String ? [@thin.hours] : @thin.hours %>
              <meta itemprop="openingHours" content="<%= hours.join(", ") %>">
              <div class="col-xs-6">
                <h3 class="medium_heading strong margin-top-0">Hours</h3>
                <ul class="list-unstyled">
                  <%= hours.map{|h| "<li class='medium_text'>#{h}</li>"}.join("\n").html_safe %>
                </ul>
              </div>
            <% elsif @thin.yp_hours.present? %>
              
              <meta itemprop="openingHours" content="<%= @thin.yp_hours.join(", ") %>">
              <div class="col-xs-6">
                <h3 class="medium_heading strong margin-top-0">Hours</h3>
                <ul class="list-unstyled">
                  <%= @thin.yp_hours.map{|h| "<li class='medium_text'>#{h.titleize}</li>"}.join("\n").html_safe %>
                </ul>
              </div>
            <% end %>
          </div>

          <% if @thin.yp_general_info.present?  %>
            <div class="row with_border">
              <div class="col-xs-12">
                 <h3 class="medium_heading strong margin-top-0">About <%= @thin.name %></h3>
                <p class="medium_text line-height-medium margin-bottom-5">
                  <%= @thin.yp_general_info %>
                </p>
              </div>
            </div>
          <% end %>
          <% if @thin.about.present? %>
            <div class="row with_border">
              <div class="col-xs-12">
                 <h3 class="medium_heading strong margin-top-0">About <%= @thin.name %></h3>
                <p class="medium_text line-height-medium margin-bottom-5">
                  <%= @thin.about %>
                </p>
              </div>
            </div>
          <% elsif !@thin.yp_general_info.present? %>
            <div class="row with_border">
              <div class="col-xs-12">
                 <h3 class="medium_heading strong margin-top-0">About <%= @thin.name %></h3>
                <h3 class="medium_text line-height-medium margin-bottom-5">
                  <%= @thin.content %>
                </h3>
              </div>
            </div>
          <% end %>

          <% if @thin.location_description.present? %>
            <div class="row with_border">
              <div class="col-xs-12">
                <h3 class="medium_heading strong margin-top-0">Location</h3>
                <h3 class="medium_text line-height-medium margin-bottom-5">
                  <%= @thin.location_description %>
                </h3>
              </div>
            </div>
          <% end %>

          <% if @thin.accreditations.present? %>
            <div class="row with_border">
              <div class="col-xs-12">
                <h3 class="medium_heading strong margin-top-0">Accreditations</h3>
                <meta itemprop="accreditations" content="<%= @thin.accreditations %>">
                <h3 class="medium_text line-height-medium margin-bottom-5">
                  <%= @thin.accreditations %>
                </h3>
              </div>
            </div>
          <% end %>

          <% if @thin.amenities.present? %>
            <div class="row with_border">
              <div class="col-xs-12">
                <h3 class="medium_heading strong margin-top-0">Amenities</h3>
                <meta itemprop="amenities" content="<%= @thin.amenities %>">
                <h3 class="medium_text line-height-medium margin-bottom-5">
                  <%= @thin.amenities %>
                </h3>
              </div>
            </div>
          <% end %>

          <% if @thin.brands.present? %>
            <div class="row with_border">
              <div class="col-xs-12">
                <h3 class="medium_heading strong margin-top-0">Brands</h3>
                <meta itemprop="brands" content="<%= @thin.brands.join(", ") %>">
                <h3 class="medium_text line-height-medium margin-bottom-5">
                  <%= @thin.brands.join(", ") %>
                </h3>
              </div>
            </div>
          <% end %>

          <% if @thin.payments.present? %>
            <div class="row with_border">
              <div class="col-xs-12">
                <h3 class="medium_heading strong margin-top-0">Payments</h3>
                <meta itemprop="payments" content="<%= @thin.payments %>">
                <h3 class="medium_text line-height-medium margin-bottom-5">
                  <%= @thin.payments %>
                </h3>
              </div>
            </div>
          <% end %>

          <div class="row with_border">
            <div class="col-xs-12">
              <h3 class="medium_heading strong margin-top-0 margin-bottom-10">Directions</h3>
              <div data-lat="<%= @thin.location['lat'] || @thin.location[:lat]  %>" data-lng="<%= @thin.location['lon'] || @thin.location[:lon] %>" id="map-canvas">
              </div>
            </div>
          </div>

          <div class="row with_border">
            <%= render :partial => "deals/reviews" %>
          </div>


        </div>
      </div>
    </div>

  </div>
</div>
<% if params[:recommend] && @recommendation %>
  <%= render :partial => "recommendations/recommend_commect_modal", :locals => {:recommendation => @recommendation, :thin => @thin} %>
<% end %>