config/routes.rb
require "subdomain"
Trenato::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get "my_pets", :to => 'users#pets', :as => "my_pets"
  resources :pets
  resources :comments
  constraints(Subdomain) do
    resources :bookmarks
    resources :recommendations
    match "/" => 'splash#welcome', :via => "get" 
    get "/myframe", :to => "splash#myframe", :as => :myframe
    get '/place/:state/:city/:service/:business_name/:id', :to => "thin#show", :as => :show_thin_city, :constraints => { :business_name => /.*/}
    get "/place/:service/:business_name/:id", :to => "thin#show", :as => :show_thin, :constraints => { :business_name => /.*/ }
    get '/search(/:page)', :to => "deals#index", :as => :search_deals, constraints: {page: /[0-9]+/}
    get '/:state/:city(/:page)', :to => "deals#index", :as => :deals, constraints: {page: /[0-9]+/}
    get '/:state/:city/:service(/:page)', :to => "deals#index", :as => :service_deals, constraints: {page: /[0-9]+/}
    get "/:state/:city/:zip(/:page)", :to => "deals#index", :as => :zip_deals, constraints: {zip: /\d\d\d\d\d/, page: /[0-9]+/}
    get "/:state/:city/:zip/:service(/:page)", :to => "deals#index", :as => :zip_service_deals, constraints: {zip: /\d\d\d\d\d/, page: /[0-9]+/}
    resources :thin do
      member do
        post :update_reviews
      end
    end
    resources :location_autocomplete, :only => [:index]
  end

  
  
  get "/about", :to => "splash#about_us"
  get "/privacy", :to => "splash#privacy"
  get "/terms", :to => "splash#terms"
  root 'pets#index'
  
  

  

end

app/views/shared/socialization/_header.html.erb
<nav class="navbar navbar-default" role="navigation"  >
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#top-navigation">
        <span class="sr-only">Navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
       <%= link_to (image_tag "logo.gif",  :id => "logo" , :height => "45").html_safe, root_path, :class => "visible-xs" %>
    </div>
    <%= link_to (image_tag "logo.gif",  :id => "logo" , :height => "45").html_safe, root_path, :class => "navbar-brand" %>
    <div class="collapse navbar-collapse" id="top-navigation">
      <ul class="nav navbar-nav navbar-left">
        <li>
          <%= link_to "social".html_safe ,root_path %>
        </li>
        <li>
          <%= link_to "video party".html_safe ,root_path %>
        </li>
        <li>
          <%= link_to "stories".html_safe ,root_path %>
        </li>
        <li>
          <%= link_to "contests".html_safe ,root_path %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown" >
          <%= link_to "share".html_safe ,"#", :class => "dropdown-toggle", :"data-toggle" => "dropdown" %>
           <ul class="dropdown-menu">
            <li><a href="#">Facebook</a></li>
            <li><a href="#">Twitter</a></li>
            <li><a href="#">More</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div>
     
  </div>
</nav>

<header class="clearfix">
  
  <nav class="navbar navbar-custom" role="navigation" >
    
  <!-- Brand and toggle get grouped for better mobile display -->
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#middle-navigation">
          <span class="sr-only">Navigation</span>
          <span class="glyphicon glyphicon-user"></span>
        </button>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="middle-navigation">
        <ul class="nav navbar-nav navbar-left my-color-panel-holder">
          <div class="my-color-panel social hidden-xs"></div>
          <li class="<%= "active" unless params[:subdomain] %>">
            <% if current_user %>
              <%= link_to '<span class="glyphicon glyphicon-plus"></span> My Pets'.html_safe , my_pets_path %>
            <% else %>
              <%= link_to '<span class="glyphicon glyphicon-plus"></span> Pets'.html_safe , my_pets_path, :class => "login" %>
            <% end %>
          </li>
        </ul>
        <form class="navbar-form navbar-left" role="search">
          <div class="form-group left-inner-addon">
            <i class="glyphicon glyphicon-search"></i> <input type="text" class="form-control" placeholder="Search">
          </div>
        </form>
        <ul class="nav navbar-nav navbar-right">
          <%  unless current_user %>
          <li>
            <%= link_to '<span class="glyphicon glyphicon-log-in"></span>&nbsp; Login'.html_safe , new_user_session_path, :class => "login" %>
          </li>
          <% else %>
          <li class="dropdown" >
            <%= link_to ((image_tag current_user.thumb, :width => "10px") +current_user.user_name).html_safe, "#", :class => "dropdown-toggle", :"data-toggle" =>  "dropdown" %>
             <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
              <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Action</a></li>
              <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Another action</a></li>
              <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Something else here</a></li>
              <li role="presentation" class="divider"></li>
              <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Separated link</a></li>
            </ul>
          </li>
          <% end %>
          <li class="dropdown" >

            <%= link_to "<span class='glyphicon glyphicon-list'></span>".html_safe ,"#", :class => "dropdown-toggle", :"data-toggle" => "dropdown" %>
            <ul class="dropdown-menu">
              <li><a href="#">Facebook</a></li>
              <li><a href="#">Twitter</a></li>
              <li><a href="#">More</a></li>
              <li class="divider"></li>
              <li><a href="#">Separated link</a></li>
            </ul>
          </li>
        </ul>
        
        
      </div><!-- /.navbar-collapse -->
       
    </div>
  </nav>
</header>