config/routes.rb
require "subdomain"
Trenato::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get "my_pets", :to => 'users#pets', :as => "my_pets"
  resources :pets
  resources :comments
  constraints(Subdomain) do
    resources :bookmarks
    resources :recommendations
    match "/" => 'splash#welcome', :via => "get" 
    get "/myframe", :to => "splash#myframe", :as => :myframe
    get '/place/:state/:city/:service/:business_name/:id', :to => "thin#show", :as => :show_thin_city, :constraints => { :business_name => /.*/}
    get "/place/:service/:business_name/:id", :to => "thin#show", :as => :show_thin, :constraints => { :business_name => /.*/ }
    get '/search(/:page)', :to => "deals#index", :as => :search_deals, constraints: {page: /[0-9]+/}
    get '/:state/:city(/:page)', :to => "deals#index", :as => :deals, constraints: {page: /[0-9]+/}
    get '/:state/:city/:service(/:page)', :to => "deals#index", :as => :service_deals, constraints: {page: /[0-9]+/}
    get "/:state/:city/:zip(/:page)", :to => "deals#index", :as => :zip_deals, constraints: {zip: /\d\d\d\d\d/, page: /[0-9]+/}
    get "/:state/:city/:zip/:service(/:page)", :to => "deals#index", :as => :zip_service_deals, constraints: {zip: /\d\d\d\d\d/, page: /[0-9]+/}
    resources :thin do
      member do
        post :update_reviews
      end
    end
    resources :location_autocomplete, :only => [:index]
  end

  
  
  get "/about", :to => "splash#about_us"
  get "/privacy", :to => "splash#privacy"
  get "/terms", :to => "splash#terms"
  root 'pets#index'
  
  

  

end

app/views/shared/_footer.html.erb
<footer class="<%= 'hidden' if params[:action] == 'myframe' %>">
  <nav class="<%= request.path == root_path ?  'navbar navbar-default navbar-inverse' : 'simple-nav navbar-inverse'   %>">
    <div class="container">
      <div class="row upper text-center">
        <div class="col-xs-12">
          <ul class="list-unstyled margin-bottom-0 list-inline small_text">
            <li><%= link_to "Terms", "/terms" %></li>
            <li><%= link_to "Privacy", "/privacy" %></li>
            <li><%= link_to "About", "/about" %></li>
            <li><%= link_to "Home", "/" %></li>
          </ul>
        </div>
      </div>
      <div class="row bottom">
        <div class="col-xs-12">
          <p class="small_text head_line">All Rights Reserved | <%= SITENAME %>® 20011–2013<span class="hidden-xs myname hidden pull-left">Designed & Developed by <%= link_to "Vipin", "http://vipinnagpal.com/", :target => "_blank" %></span></p>
        </div>
      </div>
    </div>
  </nav>
</footer>

app/views/shared/_header.html.erb
<div id="brand_top">
  <!-- <nav class="navbar navbar-top navbar-custom"> -->
  <div id="<%= 'myframe' if params[:action] == 'myframe' %>" class="navbar navbar-default navbar-custom navbar-top">
    <div class="container">
      <div class="pull-right" id="login-status">
        <% unless user_signed_in? %>
          <%= link_to "LOGIN", new_session_path(:user) ,:class => "btn btn-success bold" %>
        <% else %>
          <div class="btn-group">
            <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown">
            <%= current_user.user_name %> <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "My Account", edit_user_registration_path %></li>
              <li><%= link_to "Recommendations", recommendations_path %></li>
              <li><%= link_to "Bookmarks", bookmarks_path %></li>
              <li><%= link_to "Sign Out", destroy_session_path(:user), :method => :delete %></li>
            </ul>
          </div> 
        <% end %>
      </div>
      <div class="navbar-header">
        <%= link_to (image_tag "logo_cropped.gif",  :id => "logo").html_safe, root_path, :display => "diblock" %>
        
      </div>
      
      <div class="hidden-xs navbar-form navbar-right" id="header-form">
        <%= form_tag search_deals_path, :method => "get", :role => "search", :class => "form-inline"  do %>
        <!-- <form class="form-inline" role="search">  -->
          <div  class="form-group">
            <input type="text" name="merchant" size="30" class="form-control search_text" placeholder="Lay Bare Waxing Salon" value="<%= params[:merchant] || '' %>">
          </div>
          <div class="form-group ">
            <input type="text" name="location" size="25"   class="location_typeahead form-control" placeholder="City, state or zip"  value="<%= cookies[:location] %>">
          </div>
          <button type="submit" class="btn btn-primary btn-primary">Go</button>
        <% end %>
      </div>
      
    </div>
  </div>
  <div class="navbar navbar-default visible-xs navbar-custom" id="mobile_top_header">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="container">
      <div class="navbar-form" style="margin-top: 4px;">
        <%= form_tag search_deals_path, :method => "get", :role => "search", :class => "form-inline"  do %>
        <!-- <form class="form-inline" role="search">  -->
          <div  class="form-group">
            <input type="text" name="merchant" size="30" class="form-control search_text" placeholder="Lay Bare Waxing Salon" value="<%= params[:merchant] || '' %>">
          </div>
          <div class="form-group ">
            <input type="text" name="location"  class="form-control location_typeahead" placeholder="City, state or zip" value="<%= cookies[:location] %>">
          </div>
          <button type="submit" class="btn btn-primary">Go</button>
          <% if !params[:action] == "show" %>
            <div class="btn-group">
              <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown">
              Sort By <span class="caret"></span>
              </button>
              <ul class="dropdown-menu" role="menu">
                <li><a class="<%= 'active' if params[:sort] == 'dist' %>" href="<%= merge_with_deals_path({:sort => 'dist'}) %>">Distance</a></li>
                <li><a class="<%= 'active' if params[:sort] == 'pl' %>" href="<%= merge_with_deals_path({:sort => 'pl'}) %>">Price(Lowest First)</a></li>
                <li><a class="<%= 'active' if params[:sort] == 'dis' %>" href="<%= merge_with_deals_path({:sort => 'dis'}) %>">Discount</a></li>
                <li class="divider"></li>
              </ul>
            </div>
          <% end %>
        <% end %>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
    </div>
  </div>
</div>

<header>
  
  <nav class="navbar navbar-default navbar-inverse margin-bottom-0" role="navigation" >
  <!-- Brand and toggle get grouped for better mobile display -->
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#service_navbar">
          <span class="sr-only">Serices</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="service_navbar">
        <ul role="menu" id="accountmenu" class="nav navbar-nav">
          <li >
            <a class="<%= 'active' unless params[:service] %>" href="<%= deals_url(:state => dstate, :city => dcity, :subdomain => "places") %>">All Services</a>
          </li>
          <% Service.enabled.each do |ser| %>
            <li >
              <a class="<%= 'active' if params[:service] == ser.name %>" role="menuitem" tabindex="-1" href="<%= service_deals_url(:subdomain => "places", :state => dstate, :city => dcity, :service => ser.name) %>" > <%= ser.name %> </a>
            </li>
          <% end %>
          <!-- <%# all_cats = Category.enabled.includes(:services) %>
          <%# all_cats.slice(0,6).each do |cat| %>
            <%# services = cat.sub_categories.enabled.includes(:sub_category).all.group_by{|s| s.sub_category.name } %>
            <%# services = cat.services %>
             <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%#= cat.display_name %></a>
              <%# if services.present? %>
              <ul class="dropdown-menu list-inline" role="menu" aria-labelledby="dropdownMenu2">
                <%# services.each do |ser| %>
                    <li role="presentation" class="dropdown-header"><%#= sub_cat %></li> 
                  <%# sers.each do |ser| %> 
                    <%# next if ser.status != 'enabled' %>
                    <li role="presentation"><a role="menuitem" tabindex="-1" href="<%#= service_deals_path(:state => dstate, :city => dcity, :service => ser.name) %>"><%#= ser.name %></a></li>
                  <%# end %>
                  
                <%# end %>
              </ul>
              <%# end %>
            </li> 
          <%# end %>  -->
          <!-- <li class="dropdown" id="accountmenu">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">More..<b class="caret"></b></a>
            <ul class="dropdown-menu" style="min-width: 220px">
             <%# if all_cats.length > 5 %>
              <%# all_cats.slice(6,20).each do |cat| %>
                <li class="dropdown-submenu">
                  <a class="dropdown-toggle-submenu" href="javascrip:void(0)" tabindex="-1" ><%#= cat.name %></a>
                    <ul class="dropdown-menu list-inline clearfix">
                      <%# cat.services.each do |ser| %>
                      <%# next if ser.status != 'enabled' %>
                      <li role="presentation"><%#= link_to ser.name,  service_deals_path( :state => dstate, :city => dcity, :service => ser.name), :role => "menuitem", :tabindex => "-1" %></li>
                      <%# end %>
                    </ul>
                </li>
              <%# end %>
            <%# end %>
            </ul>
          </li> -->
        </ul>        
      </div><!-- /.navbar-collapse -->
    </div>
  </nav>
</header>

app/views/shared/_login_modal.html.erb
<div role="dialog" aria-labelledby="Login" aria-hidden="true" id="login_modal" class="my-modal modal slide">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title text-left">Login</h3>
      </div>
      <div class="modal-body">
        <%= form_for(User.new, :as => :user, :url => session_path(:user), :role => "form") do |f| %>
          <div class="form-group">
            <%= f.label :email %>
            <%= f.email_field :email, :autofocus => true, :class => "form-control reaquird", :placeholder => "Email"  %>
          </div>

          <div class="form-group">
            <%= f.label :password %>
            <%= f.password_field :password, :class => "form-control reaquird", :placeholder => "password" %>
          </div>

          <div class="form-group">
            <%= f.check_box :remember_me %> <%= f.label :remember_me %>
          </div>

          <div class="form-group clearfix margin-bottom-0">
             <p class="pull-right btn"><%= link_to "<span class='text-muted'>or</span> Sign Up".html_safe, new_user_registration_path, :class => "signup" %></p>
            <%= f.submit "Sign in", :class => "btn btn-primary pull-right" %>
          </div>
        <% end %>
      </div>
      <div class="modal-footer margin-top-0">
        Login or <%= link_to "skip this step", "", :"data-dismiss" => "modal" %>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div role="dialog" aria-labelledby="Signup" aria-hidden="true" id="signup_modal" class="my-modal modal slide">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title text-left">Sign up</h3>
      </div>
      <div class="modal-body">
        <%= form_for(User.new, :as => :user, :role => "form" , :url => registration_path(:user)) do |f| %>
        <%#= devise_error_messages! %>

          <div class="form-group" >
            <%= f.label :user_name, "Name" %>
            <%= f.text_field :user_name, :autofocus => true, :class => "form-control required", :placeholder => "Name" %>
          </div>

          <div class="form-group" >
            <%= f.label :email %>
            <%= f.email_field :email, :class => "form-control required email", :placeholder => "Email" %>
          </div>
          

          <div class="form-group" >
            <%= f.label :password %>
            <%= f.password_field :password, :class => "form-control required", :placeholder => "Password" %>
          </div>

          <div class="form-group" >
            <%= f.label :password_confirmation %>
            <%= f.password_field :password_confirmation, :class => "form-control required", :placeholder => "Confirm Password" %>
          </div>

          <div class="form-group" >
            <%= f.label :avatar, "Profile Image" %>
            <%= f.file_field :avatar %>
          </div>

          <div class="form-group clearfix margin-bottom-0">
             <p class="pull-right btn"><%= link_to "<span class='text-muted'>or</span> Sign Up".html_safe, new_user_registration_path, :class => "signup" %></p>
            <%= f.submit "Sign in", :class => "btn btn-primary pull-right" %>
          </div>

          <div class="form-group">
            <%= f.submit "Sign up", :class => "btn btn-primary" %>
            <span class="text-muted">or</span> <%= link_to "Sign in", new_session_path(:user) , :class => "login" %><br />
          </div>
      <% end %>
      </div>
      <div class="modal-footer margin-top-0">
        Login or <%= link_to "skip this step", "", :"data-dismiss" => "modal" %>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/shared/_share_bar.html.erb
<% deal_image = (deal.dealsource == "MyTime" ?  deal.showimagestandardsmall : deal.showimagestandardbig ) %>
<ul class="list-inline share_bar">
    <li>
      <%= tweet_me(deal.slug_url, deal.dealtitle.truncate(100)) %>
    </li>
    <li>
      <%= facebook_sharer(deal.slug_url) %>
    </li>
    <!-- <li><a href="mailto:email@echoecho.com?subject=SweetWords"></a> -->
    <!-- <li><a class="shared-item email" href="mailto:friend@gmail.com?subject=<%= deal.dealtitle %>&body=<%= deal.slug_url %>">Email</a></li> -->
    <li><a data-pin-config="none" onclick="return windowOpener($(this).attr('href'))"  href="//pinterest.com/pin/create/button/?url=<%= CGI::escape(deal.slug_url) %>&media=<%= CGI::escape(deal_image) %>&description=<%= deal.dealtitle %>" data-pin-do="buttonPin" class="shared-item pin" >Pin</a></li>
</ul>

app/views/shared/_splash.html.erb
<div style="margin-bottom: -29px;">
<section class="splash-top">
  <div class="bluring">
    <div class="container">
      <div class="splash">
        <div class="row">
          <div class="col-xs-12 alpha60">
            <h1 class="inverse">Find Discounted Deals and Local Appointements in your Area</h1>
            <h2 class="lead hidden-xs margin-bottom-5">Or use our <strong>powerful search</strong> to book <strong>an appointment</strong> with your 
              <strong>favorite business</strong> in your area.
            </h2>
          </div>
          <div class="col-xs-12">
            <%= form_tag search_deals_path, :method => "get", :role => "search", :class => "form-inline"  do %>
            <!-- <form class="form-inline" role="search">  -->
              <div class="form-group">
                <label class="sr-only">Where</label>
                <input type="text" name="location" size="30"   class="input-lg location_typeahead" value="<%= cookies[:location] %>" placeholder="City, state or zip">
              </div>
              <button type="submit" class="btn btn-primary btn-lg btn-green">Get Started-It's Free</button>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<section class="my-services">
  <div class="row visible-md visible-lg">
    <div class="col-md-3 cat hometint">
      <%= image_tag "railstrap/homepage_new/evolution_salon_2.jpg", :class => "hometint img-responsive"  ,:alt => "" %>
      <div class="info bluring">
        <div class="detail">
          <h3>Evolution Salon</h3>
        </div>
      </div>
    </div>
    <div class="col-md-3 cat hometint">
      <%= image_tag "railstrap/homepage_new/crystal_fitwell.jpg", :class => " hometint img-responsive",  :alt => "" %>
      <div class="info bluring">
        <div class="detail">
          <h3>Crystal Fitwell</h3>
        </div>
      </div>
    </div>
    <div class="col-md-3 cat hometint">
      <%= image_tag "railstrap/homepage_new/Pet_Keepers.jpg", :class => "hometin img-responsive",  :alt => "" %>
      <div class="info bluring">
        <div class="detail">
          <h3>Pet Keepers</h3>
        </div>
      </div>
    </div>
    <div class="col-md-3 cat hometint">
      <%= image_tag "railstrap/homepage_new/pristine_automotive_inc.jpg", :class => "hometin img-responsive", :alt => "" %>
      <div class="info bluring">
        <div class="detail">
          <h3>Pristine Automotive INC.</h3>
        </div>
      </div>
    </div>
  </div>

  <div class="row visible-md visible-lg">
    <div class="col-md-3 cat hometint lower_tint">
      <%= image_tag "railstrap/homepage_new/sunlounge_tanning_studio_7_spa.jpg", :class => "lower_tint hometint img-responsive"  ,:alt => "" %>
      <div class="info bluring">
        <div class="detail">
          <h3>Msunlounge Tanning Studio Spa Gray</h3>
        </div>
      </div>
    </div>
    <div class="col-md-3 cat hometint lower_tint">
      <%= image_tag "railstrap/homepage_new/Meyer_izaac,_od.jpg", :class => " img-responsive",  :alt => "" %>
      <div class="info bluring">
        <div class="detail">
          <h3>Meyer Izaac, OD</h3>
        </div>
      </div>
    </div>
    <div class="col-md-3 cat hometint lower_tint">
      <%= image_tag "railstrap/homepage_new/mikiSharon.jpg", :class => " img-responsive",  :alt => "" %>
      <div class="info bluring">
        <div class="detail">
          <h3>Miki Sharon</h3>
        </div>
      </div>
    </div>
    <div class="col-md-3 cat hometint lower_tint ">
      <%= image_tag "railstrap/homepage_new/YuBfit_Fitness_TRX_Personal_Training_Gym.jpg", :class => "  img-responsive",  :alt => "" %>
      <div class="info bluring">
        <div class="detail">
          <h3>YuBfit Fitness TRX Personal Training Gym</h3>
        </div>
      </div>
    </div>
  </div>

  <div class="row visible-xs visible-sm">
     <div class="col-xs-6 cat hometint">
      <%= image_tag "railstrap/homepage_new/evolution_salon_2.jpg", :class => "hometint img-responsive"  ,:alt => "" %>
      <div class="info bluring">
        <div class="detail">
          <h3>Evolution Salon</h3>
        </div>
      </div>
    </div>
    <div class="col-xs-6 cat hometint">
      <%= image_tag "railstrap/homepage_new/crystal_fitwell.jpg", :class => " hometint img-responsive",  :alt => "" %>
      <div class="info bluring">
        <div class="detail">
          <h3>Crystal Fitwell</h3>
        </div>
      </div>
    </div>
  </div>

  <div class="row visible-xs visible-sm">
    <div class="col-xs-6 cat hometint">
      <%= image_tag "railstrap/homepage_new/Pet_Keepers.jpg", :class => "hometin img-responsive",  :alt => "" %>
      <div class="info bluring">
        <div class="detail">
          <h3>Panther Energy Total Fitness</h3>
        </div>
      </div>
    </div>
    <div class="col-xs-6 cat hometint">
      <%= image_tag "railstrap/homepage_new/pristine_automotive_inc.jpg", :class => "hometin img-responsive", :alt => "" %>
      <div class="info bluring">
        <div class="detail">
          <h3>Pristine Automotive INC.</h3>
        </div>
      </div>
    </div>
  </div>

  <div class="row visible-xs visible-sm">
    <div class="col-xs-6 cat hometint lower_tint">
      <%= image_tag "railstrap/homepage_new/sunlounge_tanning_studio_7_spa.jpg", :class => "lower_tint hometint img-responsive"  ,:alt => "" %>
      <div class="info bluring">
        <div class="detail">
          <h3>Msunlounge Tanning Studio Spa Gray.jpg</h3>
        </div>
      </div>
    </div>
    <div class="col-xs-6 cat hometint lower_tint">
      <%= image_tag "railstrap/homepage_new/Meyer_izaac,_od.jpg", :class => " img-responsive",  :alt => "" %>
      <div class="info bluring">
        <div class="detail">
          <h3>Meyer Izaac, OD</h3>
        </div>
      </div>
    </div>
  </div>

  <div class="row visible-xs visible-sm">
    <div class="col-xs-6 cat hometint lower_tint">
      <%= image_tag "railstrap/homepage_new/mikiSharon.jpg", :class => " img-responsive",  :alt => "" %>
      <div class="info bluring">
        <div class="detail">
          <h3>Miki Sharon</h3>
        </div>
      </div>
    </div>
    <div class="col-xs-6 cat hometint lower_tint ">
      <%= image_tag "railstrap/homepage_new/YuBfit_Fitness_TRX_Personal_Training_Gym.jpg", :class => "  img-responsive",  :alt => "" %>
      <div class="info bluring">
        <div class="detail">
          <h3>YuBfit Fitness TRX Personal Training Gym</h3>
        </div>
      </div>
    </div>
  </div>
</section>
</div>

app/views/shared/_thin_share_bar.html.erb
<% thin_image = "" %>
<ul class="list-inline share_bar">
    <li>
      <%= tweet_me(thin.slug_url, thin.dealtitle.truncate(100)) %>
    </li>
    <li>
      <%= facebook_sharer(thin.slug_url) %>
    </li>
    <!-- <li><a href="mailto:email@echoecho.com?subject=SweetWords"></a></li> -->
   <!--  <li><a class="shared-item email" href="mailto:friend@gmail.com?subject=<%= thin.dealtitle %>&body=<%= thin.slug_url %>">Email</a></li> -->
    <li><a data-pin-config="none" onclick="return windowOpener($(this).attr('href'))"  href="//pinterest.com/pin/create/button/?url=<%= CGI::escape(thin.slug_url) %>&media=<%= CGI::escape(thin_image) %>&description=<%= thin.dealtitle %>" data-pin-do="buttonPin" class="shared-item pin" >Pin</a></li>
</ul>

app/views/shared/_zip_collector.html.erb
<div role="dialog" aria-labelledby="Zip/Postal Code" aria-hidden="true" id="zip_collector" class="modal slide">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title">Get great deals everyday or book any service from over two million businesses</h3>
      </div>
      <div class="modal-body">
        <%= form_tag get_zip_path, :role => "form", :remote => true do %>
          <div class="form-group">
            <input name="location" class="form-control zipcode required" placeholder="Zip/Postal Code" type="text" id="zip">
          </div>
          <div class="form-group clearfix margin-bottom-0">
            <%= submit_tag "Continue" , :class => "btn btn-primary pull-right", data: {:disable_with => "Submitting.."} %>
          </div>
        <% end %>
      </div>
      <div class="modal-footer margin-top-0">
        Narrow down your search or <%= link_to "skip this step", "", :"data-dismiss" => "modal" %>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->