config/routes.rb
require "subdomain"
Trenato::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get "my_pets", :to => 'users#pets', :as => "my_pets"
  resources :pets
  resources :comments
  constraints(Subdomain) do
    resources :bookmarks
    resources :recommendations
    match "/" => 'splash#welcome', :via => "get" 
    get "/myframe", :to => "splash#myframe", :as => :myframe
    get '/place/:state/:city/:service/:business_name/:id', :to => "thin#show", :as => :show_thin_city, :constraints => { :business_name => /.*/}
    get "/place/:service/:business_name/:id", :to => "thin#show", :as => :show_thin, :constraints => { :business_name => /.*/ }
    get '/search(/:page)', :to => "deals#index", :as => :search_deals, constraints: {page: /[0-9]+/}
    get '/:state/:city(/:page)', :to => "deals#index", :as => :deals, constraints: {page: /[0-9]+/}
    get '/:state/:city/:service(/:page)', :to => "deals#index", :as => :service_deals, constraints: {page: /[0-9]+/}
    get "/:state/:city/:zip(/:page)", :to => "deals#index", :as => :zip_deals, constraints: {zip: /\d\d\d\d\d/, page: /[0-9]+/}
    get "/:state/:city/:zip/:service(/:page)", :to => "deals#index", :as => :zip_service_deals, constraints: {zip: /\d\d\d\d\d/, page: /[0-9]+/}
    resources :thin do
      member do
        post :update_reviews
      end
    end
    resources :location_autocomplete, :only => [:index]
  end

  
  
  get "/about", :to => "splash#about_us"
  get "/privacy", :to => "splash#privacy"
  get "/terms", :to => "splash#terms"
  root 'pets#index'
  
  

  

end

app/models/deal.rb
class Deal < ActiveRecord::Base

  include ActiveRecordOverride

# # By default, use the GEOS implementation for spatial columns.
# self.rgeo_factory_generator = RGeo::Geos.method(:factory)

# # But use a geographic implementation for the :latlon column.
# set_rgeo_factory_for_column(:latlon, RGeo::Geographic.spherical_factory)

 acts_as_mappable :lat_column_name => :lat,
                   :lng_column_name => :lon

 serialize :neighborhoods
 serialize :modifiers
 serialize :next_appointment_times

 belongs_to :service, :primary_key => :ass_id
  if Rails.env.development?
    if File.exist? Rails.root.join("tmp","active_deal_read.txt")
      self.table_name = File.open(Rails.root.join("tmp","active_deal_read.txt"), "r") do |f| 
        name = f.read.chomp
        name.present? ? name : "deals"
      end
    else
      self.table_name = "deals"
    end
  else
    if File.exist? Rails.root.join("..", "..", "shared", "config", "active_deal_read.txt")
      self.table_name = File.open(Rails.root.join("..", "..", "shared", "config", "active_deal_read.txt"), "r")do |f| 
        name = f.read.chomp
        name.present? ? name : "deals"
      end
    else
      self.table_name = "deals"
    end
  end
 DEAL_TYPES = {1 =>"Printable Coupon",  2 => "Tip",  3 => "Sale", 4 => "Special",  5 => "Always cheap",  6 => "Coupon Code", 7 => "Happy Hour", 8 => "Free Stuff", 18381 => "Deals-of-the-Day"}

 def dealtype
  if self.userid && self.userid == 18381
    "Deals of the Day"
  elsif self.dealtypeid
    DEAL_TYPES[self.dealtypeid]
  end
 end



  def slug_path(service_name = nil)
    service_name = service_name || self.service.name
    if self.state.present? and self.city.present?
      URI.escape("/deals/view/#{service_name}/#{CGI.escape(self.name)}/#{self.id}")
    else
      URI.escape("/deals/view/#{self.state}/#{self.city}/#{service_name}/#{CGI.escape(self.name)}/#{self.id}")
    end
  end

  def slug_url
    WEBSITE_NAME + slug_path
  end

  def showlogo
    (self.dealsource == "MyTime") ?  "my_logo.png" : self.attributes["showlogo"]
  end


  
  def lng
  self.lon
  end

 

def self.near(options={})
  mappable = options[:origin]
  match_ids= options[:match]
  per_page= options[:per_page] || 40
  # url_type= URL_TYPES[options[:url_type]]
  page= options[:page] || 1
  service_id= options[:service_id]
  match_name = options[:match_name]
  explain = options[:explain]
  distance = options[:distance] || 25
  # url_type = nil
  and_query = ""#url_type ? " and url_type = #{url_type}" : ""
  
  if service_id
    and_query << " and service_id = #{service_id}"
  end
  if options[:sort_by] == "pl"
    sort_by = "dealprice asc, geo_distance asc"
  elsif options[:sort_by] == "dist"
    sort_by = "geo_distance asc"
  elsif options[:sort_by] == "dis"
    sort_by = "dealdiscountpercent desc, geo_distance asc"
  elsif match_name.present?
    sort_by = "relevance , geo_distance asc"
  else
    sort_by = "geo_distance asc"
  end

  if match_name.present?
    and_query << " and MATCH(name) AGAINST (#{self.sanitize(match_name)} IN NATURAL LANGUAGE MODE)"
  end
  select_q = ""
  if match_name.present?
    select_q << " MATCH(name) AGAINST (#{self.sanitize(match_name)} IN NATURAL LANGUAGE MODE) as relevance,"
  end

  if !match_name.present?
    and_query << " and (expirationdate is null or expirationdate < #{Time.zone.now.to_date.to_s})"
  end
  bound = GeoKit::Bounds.from_point_and_radius(mappable, distance)

sql = <<SQL
#{explain ? 'explain' : ''} select *,#{select_q} GLength(LineStringFromWKB(LineString((latlon), ((GeomFromText('Point(#{mappable.lat} #{mappable.lng})')))))) * 69 as geo_distance from #{Deal.table_name} where MBRWithin(latlon, GeomFromText('Polygon((#{bound.ne.lat} #{bound.ne.lng}, #{bound.ne.lat} #{bound.sw.lng},#{bound.sw.lat} #{bound.sw.lng},#{bound.sw.lat} #{bound.ne.lng},#{bound.ne.lat} #{bound.ne.lng}))')) #{and_query} order by #{sort_by}
SQL
deals = paginate_by_sql(sql, :page => page, :per_page => per_page, :includes => :services)
eagerLoadFor(deals, [:service])
deals
end


end

app/controllers/deals_controller.rb
class DealsController < ApplicationController

  # before_filter :set_my_location, :only => [:index]
  before_filter :set_my_location_if_wrong, :only => [:index]
  # before_filter :normalize_location, :only => [:index]


  def index
    per_page_thin = 24
    if request.path != "/search" || !params[:merchant].present?  # Search is no url type, just a convention
      @service = Service.where(:name => params[:service]).first if params[:service]
      @thins, @total_entries, @total_pages = ThinMerchant.near(origin: ThinMerchant.new(:lat => cookies[:lat] || "37.7933", :lon => cookies[:lng] || "-122.4212"), :per_page => per_page_thin, :service_id => @service.try(:id), :distance => params[:zip] ? 40 : nil, :page => params[:page] || 1)
      if params[:service] && params[:city] && [:state] && !params[:zip]
        @canonical = zip_service_deals_url(:zip => cookies[:mzip], :city => cookies[:city], :state => cookies[:state], :service => params[:service])
      elsif params[:city] && [:state] && !params[:zip]
        @canonical = zip_deals_url(:zip => cookies[:mzip], :city => cookies[:city], :state => cookies[:state] )
      end 
      # end
    elsif request.path == "/search"
      set_my_location(params[:location])
      @thins, @total_entries, @total_pages = ThinMerchant.near(origin: ThinMerchant.new(:lat => cookies[:lat] || "37.7933", :lon => cookies[:lng] || "-122.4212"), :per_page => 30, :service_id => @service.try(:id), :match_name => params[:merchant], :distance => 25, :page => params[:page] || 1)
    end
    if current_user
      @recommendations = current_user.recommendations.map(&:thin_merchant_id)
      @bookmarks = current_user.bookmarks.map(&:thin_merchant_id)
    end
    # render "index_2"
  end

  def show
    @deal = Deal.where(:id => params[:id]).first
    if @deal
      flash.now[:success] = "#{@deal.name} has been bookmarked!" if current_user && params[:bookmark] && current_user.bookmark_thin(@deal)
      flash.now[:success] = "You have successfully recommended #{@deal.name}" if current_user && params[:recommend] && current_user.recommend_thin(@deal)
      render "show"
    else
      begin
        redirect_to :back, :flash => { :error => "Sorry! Could not find the deal." }
      rescue ActionController::RedirectBackError
        redirect_to root_path, :flash => { :error => "Sorry! Could not find the deal." }
      end
    end
  end

  # def get_zip
  #   # if set_my_location(params[:mzip])
  #   #   rpath = deals_path(:state => cookies[:state], :city => cookies[:city])
  #   #   render :js => "window.location = '#{rpath}'"
  #   # else
  #   #   render :js => '$("#zip_collector form input.zipcode").next("p.t_error").remove(); $("#zip_collector form input.zipcode").after("<p class=\'t_error\'>ZIP not found! Please try a different ZIP.</p>")'
  #   # end
  # end

private


  def set_my_location_if_wrong
    if params[:city].present? && cookies[:city] != params[:city]
      set_my_location("#{params[:city]}, #{params[:state]}")
    end
  end

end

app/helpers/deals_helper.rb
module DealsHelper

  def merge_with_deals_path(additional)
    if params[:service]
      service_deals_path({:service => params[:service], :state => params[:state] || dstate, :city => params[:city] || dcity}.merge(additional))
    else
      deals_path({:state => params[:state] || dstate, :city => params[:city] || dcity}.merge(additional))
    end
  end

  def prev_page
    return nil unless (params[:page] && params[:page].to_i > 1)
    cpage = params[:page]
    if params[:service]
      service_deals_path({:service => params[:service], :page => cpage.to_i - 1, :state => params[:state] || dstate, :city => params[:city] || dcity})
    else
      deals_path({:page => cpage.to_i - 1, :state => params[:state] || dstate, :city => params[:city] || dcity})
    end
  end

  def round_to_point_five(number)
    r = (number.to_f * 2).round / 2.0
  end

  def all_ratings(thin, hide_logo_xs=true)
    # ratings = '<ul class="list-unstyled">'
    # ratings += ("<li>" + yelp_rating(thin) + "</li>") if thin.yelp_id.present? && thin.yelp_rating > 0
    # # ratings += ("<li>" + city_rating(thin) + "</li>") if thin.city_reviews.present? and thin.city_reviews[:rating] and thin.city_reviews[:rating].to_i > 0
    # ratings += "</ul>"
    ratings = yelp_rating(thin)
    ratings.html_safe
  end

  def yelp_rating(thin)
    if thin.yelp_rating.to_f > 0
      "<div class='my-small-rating'><a  target='_blank' href='http://yelp.com/biz/#{thin.yelp_id}' ><ul class='list-inline'><li><img src='#{YELP_RATING_TO_IMAGE[thin.yelp_rating.to_f]}' alt='#{thin.yelp_rating}'></li><li class='text-muted'>[#{thin.yelp_review_count}]</li><li>#{image_tag "yelp_icon@2x.png", :width => 42, :id => 'yelp_rating_image'}</li></ul></a></div>".html_safe
    else
      nil
    end
  end

  def city_rating(thin)
    if thin.city_reviews.present? && thin.city_reviews.class != Array && thin.city_reviews[:review_count].to_i > 0
      "<div class='my-small-rating'><a target='_blank' href='#{thin.city_reviews[:profile_url]}' ><ul class='list-unstyled'><li class='diblock citysearch stars_#{thin.city_reviews[:rating]} small'></li><li class='diblock text-muted'>[#{thin.city_reviews[:review_count]}]</li><li class='diblock'>#{image_tag "citysearch.jpg",  :id => 'city_rating_image'}</li></ul></a></div>".html_safe
    elsif thin.city_reviews.present? && thin.city_reviews.class == Array && thin.city_reviews.first[:review_count].to_i > 0
      rev = thin.city_reviews.first
      "<div class='my-small-rating'><a target='_blank' href='#{rev[:url]}' ><ul class='list-unstyled'><li class='diblock'><span class='citysearch stars_#{rev[:avg_rating]} small diblock'></span></li><li class='diblock text-muted'>[#{rev[:review_count]}]</li><li class='diblock'>#{image_tag "citysearch.jpg",  :id => 'city_rating_image'}</li></ul></a></div>".html_safe
    else
      nil
    end
  end

  def next_page
    cpage = params[:page] || 1
    if params[:service]
      service_deals_path({:state => params[:state] || dstate, :city => params[:city] || dcity, :service => params[:service], :page => cpage.to_i + 1})
    else
      deals_path({:page => cpage.to_i + 1, :city => params[:city] || dcity, :state => params[:state] || dstate})
    end
  end
end

app/views/deals/_deal.html.erb
<li class="deal_blk">
  <span itemprop="address" itemscope itemtype="http://schema.org/PostalAddress">
    <% if deal.address.present? %>
      <meta itemprop="streetAddress" content="<%= deal.address %>">
    <% end %>
    <% if deal.city.present? %>
      <meta itemprop="addressLocality" content="<%= deal.city %>">
    <% end %>
      <meta itemprop="addressRegion" content="<%= deal.state %>">
    <% if deal.zip.present? %>
      <meta itemprop="postalCode" content="<%= deal.zip %>">
    <% end %>
    <% if deal.phone_number %>
      <meta itemprop="telephone" content="<%= deal.phone_number %>">
    <% end %>
    <% if deal.homepage %>
      <meta itemprop="url" content="<%= deal.homepage %>">
    <% end %>
  </span>
  <% if deal.dealsource == "MyTime" %>
    <% durl = "http://www.mytime.com" + deal.url %>
  <% else %>
    <% durl = deal.url %>
  <% end %>
  <div class="image">
  <% deal_image = (deal.dealsource == "MyTime" ?  deal.showimagestandardsmall : deal.showimagestandardbig ) %>
    <%= image_tag "http://placehold.it/230x138/09f/fff&text=Image Loading..", :'data-original' =>  deal_image, :class => "lazy deal_image", :alt => deal.name %>
    <noscript><%= image_tag deal_image, :alt => deal.name, :class => "deal_image" %></noscript>
    <div class="hidden-xs">
      <div class="layer">
        <%= render :partial => "shared/share_bar", :locals => {:deal => deal} %>
      </div>
    </div>
  </div>

  <div class="deal_info">
    <h3 class="small_heaading text-muted margin-bottom-0">
      <strong><%= deal.name %></strong><br/>
      <%= deal.dealtitle %>
    </h3>
    <p class="text-left margin-bottom-0">
      <%= (deal.address.present? ?  (deal.address + ",") : "") %> <%= deal.city %><br />
      <% if deal.neighborhoods.present? %>
        <%= deal.neighborhoods.join(", ") %>
      <% end %>
    </p>
    <% if deal.avg_rating.present? && deal.avg_rating > 0 %>
      <div  itemprop="aggregateRating" itemscope itemtype="http://schema.org/AggregateRating" class="my-small-rating">
        <meta itemprop="ratingValue" content="<%= deal.avg_rating  %>" />
        <meta itemprop="reviewCount" content="<%= deal.review_count %>" />
        <div>
          <a href="<%= durl  %>" target="_blank">
            <div class="small-star-yellow small-star-<%= deal.avg_rating.to_f.to_s.gsub(".", "-") %>">
              
            </div>
            <div class="my_review_count">[<%= deal.review_count %>]</div>
          </a>
          <a href="#myrating">
            <div class="mytime-rating-logo"></div>
          </a>
        </div>
      </div>
    <% end %>
    <% if deal.expirationdate %>
      <p class="small_text text-left margin-top-0">Expires on:&nbsp;&nbsp;<%= deal.expirationdate.strftime("%A, %b %d") %></p>
    <% end %>
    <% if deal.homepage.present? %>
      <p class="text-left">
      <%= link_to deal.homepage.truncate(25), deal.homepage, :class => "strong" %>
      </p>
    <% end %>
    <% if deal.dealtype %>
    <p>
      <strong><%= deal.dealtype %></strong>
    </p>
    <% end %>
    <div class="row">
      <div class="col-xs-6"><%= link_to "View Deal", deal.slug_path, :class => "btn btn-primary btn-blue" %></div>
      <div class="col-xs-6"><%= link_to "Book Now", durl , :target => "_blank", :class => "btn btn-success" %></div>
    </div>
    <br />
    <div class="bottom-price">
      <% if deal.dealprice %>
        <% if deal.dealdiscountpercent %>
        <div class="row">
          <div class="col-xs-7"><strong><%= "$#{deal.dealprice.to_i}-$#{deal.dealoriginalprice.to_i}" %></strong></div>
          <div class="col-xs-5"><strong><%= "#{deal.dealdiscountpercent.to_i}% off"  %></strong></div>
        </div>
        <% else %>
          <div class="col-xs-12"><strong><%= "$#{deal.dealprice.to_if}" %></strong></div>
        <% end %>
      <% end %>
    </div>
    <div class="row bottom-info">
      <% if deal.showlogo %>
        <div class="sold_by">
          <div class="col-xs-6 text-left">
            <strong class="text-muted">Sold By</strong>
          </div>
          <div class="col-xs-6">
            <%= image_tag deal.showlogo %>
          </div>
        </div>
      <% elsif deal.dealsource %>
        <div class="sold_by">
          <div class="col-xs-6 text-left">
            <strong class="text-muted">Sold By</strong>
          </div>
          <div class="col-xs-6">
            <span><%= deal.dealsource %></span>>
          </div>
        </div>
      <% end %>
    </div>
  </div>

    

</li>

app/views/deals/_index_page_template.html.erb
<script type="text/template" id='map-deal-index'>
  <ul class="list-unstyled">
    <li style="max-width: 350px;">
      <div class="pull-left thin-image">
        <div class="margin-bottom-5">
          <img alt="<%%= name %>" class="thin-image img-responsive img-thumbnail" src="<%%= image %>">
        </div>
        <h3 class="margin-bottom-0 margin-top-0"><a class="upper-small-text bold" href="<%%= slug_path %>"><%%= name %></a></h3>
       <h3 class="margin-bottom-0 margin-top-0 text-muted upper-small-text bold"><%%= service %></h3>
      <p class="margin-bottom-0 margin-top-0 text-muted" style="max-width: 200px;"><%%= address %></p>
    </li>
  </ul>
</script>

app/views/deals/_thin.html.erb
<li itemscope itemtype="http://schema.org/LocalBusiness" class="deal_blk" id="deal<%= thin.id %>">
  <span itemprop="address" itemscope itemtype="http://schema.org/PostalAddress">
    <meta itemprop="streetAddress" content="<%= thin.street_address %>">
    <meta itemprop="addressLocality" content="<%= thin.city %>">
    <meta itemprop="addressRegion" content="<%= thin.state %>">
    <meta itemprop="postalCode" content="<%= thin.zip %>">
    <meta itemprop="telephone" content="<%= thin.phone_number %>">
    <meta itemprop="url" content="<%= thin.website %>">
  </span>
  <div class="image">
    <% thin_image = thin.service.image_url.try(:sample) || "" %>
    <% thin_image = thin_image.gsub("medium", "slate_black") %>
    <%= image_tag "loading.jpg", :'data-original' =>  thin_image, :class => "lazy deal_image", :alt => thin.name %>
    <noscript><%= image_tag thin_image, :alt => thin.name, :class => "deal_image" %></noscript>
    <div class="hidden-xs">
      <div class="layer">
        <% unless @already_recommended || @already_bookmarked %>
          <div class="margin-top-5">
            <%= link_to "Recommend", (thin.slug_path()+"?recommend=true"), :class => "btn btn-success" if !@recommendations || !@recommendations.include?(thin.id) %>
            <%= link_to "Bookmark", (thin.slug_path()+"?bookmark=true"), :class => "btn btn-success" if !@bookmarks || !@bookmarks.include?(thin.id) %>
          </div>
        <% end %>
        <% if @already_bookmarked %>
          <%= link_to "Unbookmark", bookmark_path(bookmark), :class => "btn btn-zomato-gray", :method => :delete  %>
        <% end %>
        <%= render :partial => "shared/thin_share_bar", :locals => {:thin => thin} %>
      </div>
    </div>
  </div>

  <div class="deal_info">
    <h3 class="margin-bottom-0 small_heading margin-bottom-0">
      <span class="bold dblock"><%= thin.name %></span>
      <span class="service"><%= thin.service.name %></span>
    </h3>

    <p class="address text-left margin-bottom-0 text-muted">
      <%= thin.full_address %>
    </p>
    <% if thin.neighborhoods.present? %>
      <p class="text-left margin-bottom-0 text-muted">
        <%= thin.neighborhoods.slice(0,2).join(", ") %>
      </p>
    <% end %>
    <% if thin.recommendations_count > 0 %>
      <p class="address text-left margin-bottom-0 text-muted">
        <em>Recommended by  <strong><%= thin.recommendations_count %></strong> <%= thin.recommendations_count > 1 ? " users" : " user" %></em> [ <%= link_to "view", thin.slug_path %> ]
      </p>
    <% end %>

    <% if thin.bookmarks_count > 0 %>
      <p class="address text-left margin-bottom-0 text-muted">
        <em>Bookmarked by  <strong><%= thin.bookmarks_count %></strong> <%= thin.bookmarks_count > 1 ? " users" : " user" %></em> [ <%= link_to "view", thin.slug_path %> ]
      </p>
    <% end %>
    <div class="clearfix">
      <ul class="text-left list-inline margin-bottom-5 tile-links">
        <li>
          <%= link_to "View More", thin.slug_path, :class => "slug" %>
        </li>
        <% if thin.website.present? %>
          <li>
            | <%= link_to 'Website', thin.website, :target => "_blank" %>
          </li>
        <% end %>
        <li class="dblock" style=""><%= link_to_iframe "Request Appointment", thin.my_slug_path(thin.service.name, thin.service.category.name), :class => "text-left" %></li>
      </ul>
    </div>

    

    <% yelpr = yelp_rating(thin) %>
    <% cityr = city_rating(thin) %>
    
      <div class="bottom-price text-left">
  <!--       <%# if thin.min_price %>
          <div class="col-xs-12"><strong><%#= "$#{thin.min_price}" %></strong></div>
        <%# end %> -->
        <%= yelpr %>
        <%= cityr %>
      </div>
   
    <!-- <p class="small_text text-left text-muted"><span class="strong">Note:</span> Request appointment to know prices.</p> -->
    <div class="text-left bottom-info">
      
      <!-- <div  itemprop="aggregateRating" itemscope itemtype="http://schema.org/AggregateRating" class="my-small-rating">
        <meta itemprop="ratingValue" content="" />
        <meta itemprop="reviewCount" content="" />
        <div>
          <a href="">
            <div class="small-star-yellow small-star-">
              
            </div>
            <div class="my_review_count">()</div>
          </a>
          <a href="#myrating">
            <div class="mytime-rating-logo"></div>
          </a>
        </div>
      </div> -->
    </div>
  </div>
</li>

app/views/deals/_thin_2.html.erb
<li id="deal<%= thin.id %>" class="business-index" itemscope itemtype="http://schema.org/LocalBusiness" class="deal_blk">
  <span itemprop="address" itemscope itemtype="http://schema.org/PostalAddress">
    <meta itemprop="streetAddress" content="<%= thin.street_address %>">
    <meta itemprop="addressLocality" content="<%= thin.city %>">
    <meta itemprop="addressRegion" content="<%= thin.state %>">
    <meta itemprop="postalCode" content="<%= thin.zip %>">
    <meta itemprop="telephone" content="<%= thin.phone_number %>">
    <meta itemprop="url" content="<%= thin.website %>">
  </span>
  <div class="row with_border_bottom clearfix busi-info-section">
    <div class="col-sm-12 col-xs-12">
      <ul class="list-unstyled">
        <li style="min-width: 350px;">
          <div class="pull-left thin-image">
            <div class="margin-bottom-5">
              <%= image_tag thin.service.image_url.sample.gsub("medium", "slate_black"), :class => "thin-image img-responsive img-thumbnail", :"data-original" => thin.service.image_url.sample.gsub("medium", "slate_black") %>
            </div>
            <%= all_ratings(thin, true) %>
          </div>
          <h3 class="margin-bottom-0 margin-top-0"><%= link_to thin.name, thin.slug_path, :class => "medium_text bold" %></h3>
           <h4 class="margin-bottom-0 margin-top-0 text-muted medium_text"><%= thin.service.name %></h4>
          <p class="margin-bottom-0 margin-top-0 text-muted"><%= thin.full_address %></p>
          <% if thin.hours.present? %>
            <p class="margin-bottom-0 margin-top-0 text-muted"><%= thin.hours.join(", ") %></p>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</li>